[package]
name = "ducoflux"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.2"
influxdb = "0.7"
tokio = { version = "1.34", features = ["full"] }  # Replace X.Y with the latest version
regex = "1.10"

